### ISSUE TITLE
use libdoc.py to generate documentation

### ISSUE THREAD

**Issue by bulkan** [MarketSquare/robotframework-difflibrary#1]

**Comment by vkosuri** [comment]
https://github.com/robotframework/robotframework/issues/2462

**Comment by vkosuri** [comment]
@pekkaklarck I was pointing libdoc to keywords 

``` Bash
python -m robot.libdoc src/DiffLibrary/keywords.py doc/DiffLibrary.html
```

but it has dependency in other file, thats the reason i couldn't get keywords html file. It is working with

``` Bash
python -m robot.libdoc src/DiffLibrary doc/DiffLibrary.html
```

Thanks, It was documented here http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#libdoc

**Comment by vkosuri** [comment]
@bulkan thank you, could you please update doc link project header field?

**Comment by vkosuri** [comment]
@bulkan thanks, I have updated in README file
