### ISSUE TITLE
Transfer ownership to MarketSquare?

### ISSUE THREAD

**Issue by bulkan** [MarketSquare/robotframework-difflibrary#12]
Hi @lucagiove,

I see yourself and others are taking good care of https://github.com/MarketSquare/robotframework-requests and I was thinking if you would like to take ownership of this library as well as https://github.com/bulkan/robotframework-archivelibrary ?

**Comment by lucagiove** [comment]
I'll see what I can do, for sure someone from the community can help.
The difference is that I personally don't use those libraries but moving under MarketSquare is the right choice, thanks!

**Comment by vkosuri** [comment]
I do agree

**Comment by lucagiove** [comment]
Once back from vacation I'll work on it.

Il mar 18 ago 2020, 04:20 Mallikarjunarao Kosuri <notifications@github.com>
ha scritto:

**Comment by bulkan** [comment]
Thanks you @lucagiove

**Comment by lucagiove** [comment]
Hi @bulkan, I've discussed in the last RF Open Space last week about your suggestion.
There is interests of @emanlove and @acaovilla in becoming maintainers, I can also help but not as lead maintainer.
Whenever you're ready to proceed with the transfer I think @hi-fi will help in setting up the right permissions.

Thank you and kind regards,
Luca

**Comment by lucagiove** [comment]
Hi @bulkan I don't recall how you did transfer requests library i think you transferred directly to MarketSquare.
Remember also add me or someon as maintainer on PyPi.

**Comment by bulkan** [comment]
@lucagiove I've transferred it to @MarketSquare now and added you on PyPI :)

**Comment by lucagiove** [comment]
Cool thanks!
