### ISSUE TITLE
Not installable with pip

### ISSUE THREAD

**Issue by Tattoo** [MarketSquare/robotframework-difflibrary#2]
$ pip install -U robotframework-difflibrary
Downloading/unpacking robotframework-difflibrary
  Could not find a version that satisfies the requirement robotframework-difflibrary (from versions: 0.1dev)
Cleaning up...
No distributions matching the version for robotframework-difflibrary
Storing debug log for failure in /home/tkairi/.pip/pip.log

**Comment by antonpiatek** [comment]
try adding _--pre_

**Comment by bulkan** [comment]
fixed in 4c9a2137ef1aa46642208cd81675f416dfec9b94
